# Generated by Django 4.1.1 on 2022-09-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220916_1744'),
        ('catalog', '0004_alter_author_options_alter_author_date_of_death'),
    ]

    operations = [
    ]
